# this file is not designed to be run directly
# instead, use the docker-compose.<os>.<swift> files
# eg docker-compose -f docker/docker-compose.yaml -f docker/docker-compose.1804.50.yaml run test
version: "3"

services:

  runtime-setup:
    image: vscode-swift:default
    build:
      context: .
      dockerfile: Dockerfile

  common: &common
    image: vscode-swift:default
    depends_on: [runtime-setup]
    volumes:
      - ~/.ssh:/root/.ssh
      - ..:/code:z
    working_dir: /code
    environment:
      - NPM_CONFIG_PREFIX=/tmp/node_modules
    cap_drop:
      - CAP_NET_RAW
      - CAP_NET_BIND_SERVICE

  soundness:
    <<: *common
    command: /bin/bash -xcl "./scripts/soundness.sh"

  test:
    <<: *common
    environment:
      - NPM_CONFIG_PREFIX=/tmp/node_modules    
    command: /bin/bash -xcl "npm ci && npm run format && npm run compile && npm run package"

  shell:
    <<: *common
    entrypoint: /bin/bash
