# this file is not designed to be run directly
# instead, use the docker-compose.<os>.<swift> files
# eg docker-compose -f docker/docker-compose.yaml -f docker/docker-compose.1804.50.yaml run test

services:

  runtime-setup:
    image: vscode-swift:default
    build:
      context: .
      dockerfile: Dockerfile

  common: &common
    image: vscode-swift:default
    environment:
      - CI=1
    depends_on: [runtime-setup]
    volumes:
      - ~/.ssh:/root/.ssh
      - ..:/code:z
    working_dir: /code
    user: vscode:vscode
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_PTRACE
    cap_drop:
      - CAP_NET_RAW
      - CAP_NET_BIND_SERVICE

  soundness:
    <<: *common
    command: /bin/bash -xcl "./scripts/soundness.sh"

  test:
    <<: *common
    command: /bin/bash -xcl "./docker/test.sh"

  shell:
    <<: *common
    entrypoint: /bin/bash
